server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.106.200.230:3306/spring_cloud_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  driver-class-name: org.gjt.mm.mysql.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zjj.springcloud.entities    # 所有Entity别名类所在包